//	This program displays three rows of numbers.

#include <iostream.h>

void main(void)
{
	int num1 = 2897, num2 = 5,    num3 = 837,
	    num4 = 34,   num5 = 7,    num6 = 1623,
        num7 = 390,  num8 = 3456, num9 = 12;
	
	// Display the first row of numbers
	cout << num1 << "  "; 
	cout << num2 << "  "; 
	cout << num3 << endl;

	// Display the second row of numbers
	cout << num4 << "  "; 
	cout << num5 << "  "; 
	cout << num6 << endl;

	// Display the third row of numbers
	cout << num7 << "  ";
	cout << num8 << "  "; 
	cout << num9 << endl;
}
